preload = .config/backgrounds/wallpaper.png

wallpaper {
    monitor = DP-2
    path = ~/.config/backgrounds/wallpaper.png
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/.config/backgrounds/wallpaper.png
}

splash = false
ipc = true
