# Default its set for all keyboards but you can specify using: keyd -m
# [ids]
# ID

[control]
alt = swap(altgr)

[alt]
control = swap(altgr)

[altgr]
f1 = macro(leftcontrol+leftalt+f1)
f2 = macro(leftcontrol+leftalt+f2)
f3 = macro(leftcontrol+leftalt+f3)
f4 = macro(leftcontrol+leftalt+f4)
f5 = macro(leftcontrol+leftalt+f5)
f6 = macro(leftcontrol+leftalt+f6)
f7 = macro(leftcontrol+leftalt+f7)
f8 = macro(leftcontrol+leftalt+f8)
f9 = macro(leftcontrol+leftalt+f9)
f10 = macro(leftcontrol+leftalt+f10)
f11 = macro(leftcontrol+leftalt+f11)
f12 = macro(leftcontrol+leftalt+f12)







